### Next Steps:

**The following for the CNN architecture first:**
- make models flexible to differnt input lengths and for amino aids
- create orchestrator to train
    - one model
    - with one specific hyperparameter setting
    - for one dataset using pytorch-lightning (not in container)
- integrate hyperparameter search and think about tracking that using ml-flow

In [1]:
from pathlib import Path

def print_tree(root_dir, prefix=""):
    root = Path(root_dir)
    entries = sorted(root.iterdir(), key=lambda x: (x.is_file(), x.name.lower()))

    for i, entry in enumerate(entries):
        connector = "└── " if i == len(entries) - 1 else "├── "
        print(prefix + connector + entry.name)

        if entry.is_dir():
            extension = "    " if i == len(entries) - 1 else "│   "
            print_tree(entry, prefix + extension)

print_tree('C:/Users/kroep/Desktop/AI/ssl-for-ood-molecules')

├── .git
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   ├── sendemail-validate.sample
│   │   └── update.sample
│   ├── info
│   │   └── exclude
│   ├── logs
│   │   ├── refs
│   │   │   ├── heads
│   │   │   │   └── main
│   │   │   └── remotes
│   │   │       └── origin
│   │   │           └── main
│   │   └── HEAD
│   ├── objects
│   │   ├── 09
│   │   │   └── 9123f24b0b4ebe8dbb24136f13156acf82f98e
│   │   ├── 1c
│   │   │   └── d11c0e08b6dfdff4b65aa7b488d36f5d248292
│   │   ├── 23
│   │   │   └── 5b6b29bddfff301a13893be442e2f8b69cf79f
│   │   ├── 2b
│   │   │   └── 008a2c04f6a8cf3eed39d309dcd41f49f2f3da
│   │   ├── 2d
│   │   │   └── 0285d371a75e1d44aa9e1fe7a9e5aa75f1770a
│   │   ├── 2e
│   │   │   └── 5993ce37b75fccfbf2ae108893789fb51e28bd
│   │   ├── 44
│   │   │   └── cc20322f09fef2f92c7a889aaabcbee70669a6
│   │   ├── 48
│   │   │   └── b89e8b405f9dba7538df94c73b8619a993be7e
│   │   ├── 5a
│   │   │   └── 7f7f78b58e78c995f05fdd44ee9ab49d333e12
│   │   ├── 5d
│   │   │   └── 4941ed0bfd3a4a47834aa9527c34a1688f72f8
│   │   ├── 67
│   │   │   └── 961332e008d255b52388648cd49cc35e0c09ae
│   │   ├── 6e
│   │   │   └── 4af1c414d3fa8256407867786f209ce27b11ae
│   │   ├── 74
│   │   │   └── 1601d0b33edf2ef26e51d39da0ee894d647197
│   │   ├── 7e
│   │   │   └── 7b7a4fc3649096500a89a90df250e87dea8551
│   │   ├── 7f
│   │   │   └── 8928d6bff887b3baabc6385209e8f78081f2e8
│   │   ├── 92
│   │   │   └── 13335648f744bf5f3cce42975e7189743ee86f
│   │   ├── 9d
│   │   │   ├── 1dcfdaf1a6857c5f83dc27019c7600e1ffaff8
│   │   │   └── 752135d10e4ebe90761460bfbafae5e5b21237
│   │   ├── 9f
│   │   │   └── 2c8ced057b2962b2b769e12791096dd4b7c291
│   │   ├── c3
│   │   │   └── 785f34f0a54ffbd46cf826ba638d95693f2935
│   │   ├── c4
│   │   │   └── a5a868020bbfbce82dbb963a7332e508b6eb8a
│   │   ├── d1
│   │   │   └── 6c585f50c64624073ec7b9c9baae4b8c00af57
│   │   ├── dc
│   │   │   └── 81d0923a9b13dfeeddc3291a75f685e417b987
│   │   ├── e2
│   │   │   └── d0e056baf5a41cd698229463530b9453c438f5
│   │   ├── e6
│   │   │   └── 9de29bb2d1d6434b8b29ae775ad8c2e48c5391
│   │   ├── fa
│   │   │   └── ec9494199a6bc907623435bdfcf88b541396e6
│   │   ├── info
│   │   └── pack
│   ├── refs
│   │   ├── heads
│   │   │   └── main
│   │   ├── remotes
│   │   │   └── origin
│   │   │       └── main
│   │   └── tags
│   ├── COMMIT_EDITMSG
│   ├── config
│   ├── description
│   ├── FETCH_HEAD
│   ├── HEAD
│   ├── index
│   └── ORIG_HEAD
├── .ipynb_checkpoints
│   ├── notes-checkpoint.txt
│   ├── pipeline-checkpoint.ipynb
│   ├── pyproject-checkpoint.toml
│   └── README-checkpoint.md
├── config
│   ├── cnn
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   ├── cnn_lstm
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   ├── cnn_old
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   ├── lstm
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   ├── lstm_cnn
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   ├── mlp
│   │   ├── aav.yaml
│   │   ├── base.yaml
│   │   ├── gfp.yaml
│   │   ├── search_space.yaml
│   │   └── tfbind8.yaml
│   └── transformer
│       ├── aav.yaml
│       ├── base.yaml
│       ├── gfp.yaml
│       ├── search_space.yaml
│       └── tfbind8.yaml
├── data
│   ├── aav
│   │   ├── preprocessed
│   │   │   ├── target_unlabeled.npz
│   │   │   ├── test.npz
│   │   │   ├── train.npz
│   │   │   ├── val_id.npz
│   │   │   ├── val_ood.npz
│   │   │   └── y_scaler.npz
│   │   └── splits
│   │       ├── .ipynb_checkpoints
│   │       │   └── metadata-checkpoint.txt
│   │       ├── metadata.txt
│   │       ├── target_unlabeled.csv
│   │       ├── test.csv
│   │       ├── train.csv
│   │       ├── val_id.csv
│   │       └── val_ood.csv
│   ├── avv
│   │   └── preprocessed
│   ├── gb1
│   │   ├── preprocessed
│   │   │   ├── target_unlabeled.npz
│   │   │   ├── test.npz
│   │   │   ├── train.npz
│   │   │   ├── val_id.npz
│   │   │   ├── val_ood.npz
│   │   │   └── y_scaler.npz
│   │   └── splits
│   │       ├── metadata.txt
│   │       ├── target_unlabeled.csv
│   │       ├── test.csv
│   │       ├── train.csv
│   │       ├── val_id.csv
│   │       └── val_ood.csv
│   ├── gfp
│   │   ├── preprocessed
│   │   │   ├── target_unlabeled.npz
│   │   │   ├── test.npz
│   │   │   ├── train.npz
│   │   │   ├── val_id.npz
│   │   │   ├── val_ood.npz
│   │   │   └── y_scaler.npz
│   │   └── splits
│   │       ├── metadata.txt
│   │       ├── target_unlabeled.csv
│   │       ├── test.csv
│   │       ├── train.csv
│   │       ├── val_id.csv
│   │       └── val_ood.csv
│   └── tfbind8
│       ├── preprocessed
│       │   ├── target_unlabeled.npz
│       │   ├── test.npz
│       │   ├── train.npz
│       │   ├── val_id.npz
│       │   ├── val_ood.npz
│       │   └── y_scaler.npz
│       └── splits
│           ├── metadata.txt
│           ├── target_unlabeled.csv
│           ├── test.csv
│           ├── train.csv
│           ├── val_id.csv
│           └── val_ood.csv
├── notebooks
│   ├── .ipynb_checkpoints
│   │   ├── explore_data-checkpoint.ipynb
│   │   ├── load_data-checkpoint.ipynb
│   │   └── train_benchmarks-checkpoint.ipynb
│   ├── explore_data.ipynb
│   ├── load_data.ipynb
│   ├── train_benchmarks.ipynb
│   └── train_benchmarks_avv.ipynb
├── reports
├── results
│   ├── data_exploration
│   │   ├── aav
│   │   │   ├── delta_label_by_delta_mut_dist_box.png
│   │   │   ├── label_by_mut_dist_box.png
│   │   │   ├── label_by_mut_dist_mean_ci.png
│   │   │   ├── label_distribution.png
│   │   │   └── mut_dist_hist.png
│   │   ├── gfp
│   │   │   ├── delta_label_by_delta_mut_dist_box.png
│   │   │   ├── label_by_mut_dist_box.png
│   │   │   ├── label_by_mut_dist_mean_ci.png
│   │   │   ├── label_distribution.png
│   │   │   └── mut_dist_hist.png
│   │   └── tfbind8
│   │       ├── delta_label_by_delta_mut_dist_box.png
│   │       ├── label_by_mut_dist_box.png
│   │       ├── label_by_mut_dist_mean_ci.png
│   │       ├── label_distribution.png
│   │       └── mut_dist_hist.png
│   └── training
│       ├── cnn
│       │   ├── aav
│       │   │   └── cnn_aav_manual_run
│       │   │       ├── checkpoints
│       │   │       │   ├── best-v1.ckpt
│       │   │       │   ├── best-v2.ckpt
│       │   │       │   ├── best-v3.ckpt
│       │   │       │   └── best.ckpt
│       │   │       ├── lightning_logs
│       │   │       │   └── version_0
│       │   │       │       ├── hparams.yaml
│       │   │       │       └── metrics.csv
│       │   │       ├── config.yaml
│       │   │       ├── metrics.json
│       │   │       ├── mlflow_run_id.txt
│       │   │       ├── model_state_dict.pt
│       │   │       └── y_scaler.json
│       │   ├── gfp
│       │   │   └── cnn_gfp_manual_run
│       │   │       ├── checkpoints
│       │   │       │   ├── best-v1.ckpt
│       │   │       │   ├── best-v2.ckpt
│       │   │       │   ├── best-v3.ckpt
│       │   │       │   └── best.ckpt
│       │   │       ├── lightning_logs
│       │   │       │   └── version_0
│       │   │       │       ├── hparams.yaml
│       │   │       │       └── metrics.csv
│       │   │       ├── config.yaml
│       │   │       ├── metrics.json
│       │   │       ├── mlflow_run_id.txt
│       │   │       ├── model_state_dict.pt
│       │   │       └── y_scaler.json
│       │   └── tfbind8
│       │       └── cnn_tfbind8_manual_run
│       │           ├── checkpoints
│       │           │   ├── best-v1.ckpt
│       │           │   ├── best-v2.ckpt
│       │           │   ├── best-v3.ckpt
│       │           │   ├── best-v4.ckpt
│       │           │   ├── best-v5.ckpt
│       │           │   ├── best-v6.ckpt
│       │           │   └── best.ckpt
│       │           ├── lightning_logs
│       │           │   ├── version_0
│       │           │   │   ├── hparams.yaml
│       │           │   │   └── metrics.csv
│       │           │   ├── version_1
│       │           │   │   ├── hparams.yaml
│       │           │   │   └── metrics.csv
│       │           │   ├── version_2
│       │           │   │   ├── hparams.yaml
│       │           │   │   └── metrics.csv
│       │           │   ├── version_3
│       │           │   │   ├── hparams.yaml
│       │           │   │   └── metrics.csv
│       │           │   └── version_4
│       │           │       ├── hparams.yaml
│       │           │       └── metrics.csv
│       │           ├── config.yaml
│       │           ├── metrics.json
│       │           ├── mlflow_run_id.txt
│       │           ├── model_state_dict.pt
│       │           └── y_scaler.json
│       └── lstm
│           ├── aav
│           │   └── lstm_aav_manual_run
│           │       ├── checkpoints
│           │       │   ├── best-v1.ckpt
│           │       │   └── best.ckpt
│           │       ├── config.yaml
│           │       ├── metrics.json
│           │       ├── mlflow_run_id.txt
│           │       ├── model_state_dict.pt
│           │       └── y_scaler.json
│           ├── gfp
│           │   └── lstm_gfp_manual_run
│           │       ├── checkpoints
│           │       │   └── best.ckpt
│           │       ├── config.yaml
│           │       ├── metrics.json
│           │       ├── mlflow_run_id.txt
│           │       ├── model_state_dict.pt
│           │       └── y_scaler.json
│           └── tfbind8
│               └── lstm_tfbind8_manual_run
│                   ├── checkpoints
│                   │   └── best.ckpt
│                   ├── config.yaml
│                   ├── metrics.json
│                   ├── mlflow_run_id.txt
│                   ├── model_state_dict.pt
│                   └── y_scaler.json
├── src
│   ├── ssl_for_ood
│   │   ├── .ipynb_checkpoints
│   │   ├── __pycache__
│   │   │   └── __init__.cpython-311.pyc
│   │   ├── architectures
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-311.pyc
│   │   │   │   ├── _base.cpython-311.pyc
│   │   │   │   ├── cnn.cpython-311.pyc
│   │   │   │   ├── cnn_lstm.cpython-311.pyc
│   │   │   │   ├── lstm.cpython-311.pyc
│   │   │   │   ├── lstm_cnn.cpython-311.pyc
│   │   │   │   ├── mlp.cpython-311.pyc
│   │   │   │   └── transformer.cpython-311.pyc
│   │   │   ├── __init__.py
│   │   │   ├── _base.py
│   │   │   ├── cnn.py
│   │   │   ├── cnn_lstm.py
│   │   │   ├── lstm.py
│   │   │   ├── lstm_cnn.py
│   │   │   ├── mlp.py
│   │   │   └── transformer.py
│   │   ├── architectures_old
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-311.pyc
│   │   │   │   └── cnn.cpython-311.pyc
│   │   │   ├── __init__.py
│   │   │   └── cnn.py
│   │   ├── data
│   │   │   ├── .ipynb_checkpoints
│   │   │   │   └── load_data_old-checkpoint.py
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-311.pyc
│   │   │   │   ├── io.cpython-311.pyc
│   │   │   │   ├── load_data.cpython-311.pyc
│   │   │   │   └── preprocess_data.cpython-311.pyc
│   │   │   ├── __init__.py
│   │   │   ├── load_data.py
│   │   │   ├── load_data_old.py
│   │   │   ├── preprocess_data.py
│   │   │   └── preprocess_data_old.py
│   │   ├── training
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-311.pyc
│   │   │   │   ├── datasets.cpython-311.pyc
│   │   │   │   ├── lightning_module.cpython-311.pyc
│   │   │   │   └── trainer.cpython-311.pyc
│   │   │   ├── __init__.py
│   │   │   ├── datasets.py
│   │   │   ├── lightning_module.py
│   │   │   ├── search.py
│   │   │   └── trainer.py
│   │   ├── training_old
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-311.pyc
│   │   │   │   ├── datasets.cpython-311.pyc
│   │   │   │   ├── datasets.cpython-313.pyc
│   │   │   │   ├── lightning_module.cpython-311.pyc
│   │   │   │   ├── lightning_module.cpython-313.pyc
│   │   │   │   ├── search.cpython-311.pyc
│   │   │   │   ├── search.cpython-313.pyc
│   │   │   │   ├── trainer.cpython-311.pyc
│   │   │   │   └── trainer.cpython-313.pyc
│   │   │   ├── __init__.py
│   │   │   ├── datasets.py
│   │   │   ├── lightning_module.py
│   │   │   ├── search.py
│   │   │   └── trainer.py
│   │   └── __init__.py
│   └── ssl_for_ood_molecules.egg-info
│       ├── .ipynb_checkpoints
│       │   └── PKG-INFO-checkpoint
│       ├── dependency_links.txt
│       ├── PKG-INFO
│       ├── SOURCES.txt
│       └── top_level.txt
├── .gitignore
├── config.yaml
├── notes.txt
├── pipeline.ipynb
├── pyproject.toml
├── README.md
├── requirements.txt
├── result_AAV.json
├── result_GFP.json
└── result_TFBind8.json

In [2]:
'src.md'.split('.')

['src', 'md']

### Imports

In [3]:
import torch
if torch.cuda.is_available():
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print('No GPU found')
    
from sklearn.model_selection import train_test_split
from collections import Counter
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.lines import Line2D
import os
import re
import numpy as np
from collections import defaultdict
import random
import json
import time

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import pandas as pd

#from models.benchmarks.cnn_lstm_model import train_cnn_lstm_from_config

#from models.benchmarks.mlp_model import train_mlp_from_config
#from models.benchmarks.cnn_model import train_cnn_from_config
#from models.benchmarks.lstm_model import train_lstm_from_config
#from models.benchmarks.lstm_cnn_model import train_lstm_cnn_from_config
#from models.benchmarks.cnn_lstm_model import train_cnn_lstm_from_config
#from models.benchmarks.transformer_model import train_transformer_from_config
#from functions.evaluate_best_models import run_evaluation
#from functions.evaluate_best_models import predict_y_values

#from functions.random_search import random_search

from huggingface_hub import hf_hub_download

Using GPU: NVIDIA GeForce GTX 1660 SUPER

### Load data

In [4]:
from ssl_for_ood.data.load_data import load_all_data
all_data = load_all_data()

### Preprocess data

In [5]:
from ssl_for_ood.data.preprocess_data import preprocess_all_data
all_prep_data = preprocess_all_data(overwrite=True)

### Load preprocessed datasets

In [6]:
datasets = ['GFP', 'AAV', 'TFBind8']
data_dict_df = {dataset: {} for dataset in datasets}
data_dict_np = {dataset: {} for dataset in datasets}

for split in ['train', 'val_id', 'val_ood', 'test']:
    data_dict_df['GFP'][split] = pd.read_csv(os.path.join('data', 'gfp', 'splits', f'{split}.csv'))
    data_dict_df['AAV'][split] = pd.read_csv(os.path.join('data', 'aav', 'splits', f'{split}.csv'))
    data_dict_df['TFBind8'][split] = pd.read_csv(os.path.join('data', 'tfbind8', 'splits', f'{split}.csv'))

for split in ['train', 'val_id', 'val_ood', 'test']:
    data_dict_np['GFP'][split] = {
        'x': np.load(os.path.join('data', 'gfp', 'preprocessed', f'{split}.npz'))['x'],
        'y': np.load(os.path.join('data', 'gfp', 'preprocessed', f'{split}.npz'))['y']
    }
    data_dict_np['AAV'][split] = {
        'x': np.load(os.path.join('data', 'aav', 'preprocessed', f'{split}.npz'))['x'],
        'y': np.load(os.path.join('data', 'aav', 'preprocessed', f'{split}.npz'))['y']
    }
    data_dict_np['TFBind8'][split] = {
        'x': np.load(os.path.join('data', 'tfbind8', 'preprocessed', f'{split}.npz'))['x'],
        'y': np.load(os.path.join('data', 'tfbind8', 'preprocessed', f'{split}.npz'))['y']
    }

### Train Models

**Think about:**
- saving results
- ML Flow

In [7]:
import numpy as np
from ssl_for_ood.data.preprocess_data import load_y_scaler, transform_y, inverse_transform_y

scaler = load_y_scaler("aav")

y = np.array([-1, 0, 1, 2, 5], dtype=np.float32)

y_scaled = transform_y(y, scaler)
y_back = inverse_transform_y(y_scaled, scaler)

### ML-Flow

In [8]:
import mlflow

### Train RF Baseline

In [11]:
import time
import json
import numpy as np
import mlflow
import mlflow.sklearn

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error


# -----------------------------
# MLflow setup
# -----------------------------
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("ssl_ood_rf_baseline")

# Optional but useful
RUN_GROUP = "rf_baseline_v1"

rf_results = {dataset: [] for dataset in datasets}

for i, dataset in enumerate(datasets):
    with mlflow.start_run(run_name=f"rf_{dataset}"):
        best_mae = float("inf")
        rf_scorer = None
        best_n_trees = None

        x_train = data_dict_np[dataset]["train"]["x"]
        y_train = data_dict_np[dataset]["train"]["y"].ravel()

        x_val = data_dict_np[dataset]["val_id"]["x"]
        y_val = data_dict_np[dataset]["val_id"]["y"].ravel()

        x_test = data_dict_np[dataset]["test"]["x"]
        y_test = data_dict_np[dataset]["test"]["y"].ravel()

        n_trees = 3

        print(f"Predicting for {dataset} using {n_trees} trees")
        start_time = time.time()

        rf = RandomForestRegressor(
            n_estimators=n_trees,
            random_state=42 + i,
            n_jobs=1
        )
        rf.fit(x_train, y_train)

        y_pred_val = rf.predict(x_val)
        mae_val = mean_absolute_error(y_val, y_pred_val)

        if mae_val < best_mae:
            best_mae = mae_val
            rf_scorer = rf
            best_n_trees = n_trees

        y_pred_test = rf_scorer.predict(x_test)
        mae_test = mean_absolute_error(y_test, y_pred_test)
        error_std_test = np.std(np.abs(y_pred_test - y_test))
        error_se_test = error_std_test / np.sqrt(len(y_test))
        runtime_sec = time.time() - start_time

        result = {
            "model": "rf",
            "model_num": i,
            "dataset": dataset,
            "hyperparams": {"n_trees": best_n_trees},
            "n_trees": best_n_trees,
            "val_id_mae": float(best_mae),
            "test_mae": float(mae_test),
            "test_std": float(error_std_test),
            "test_se": float(error_se_test),
        }

        rf_results[dataset].append(result)

        # -----------------------------
        # Log params
        # -----------------------------
        mlflow.log_param("model", "RandomForestRegressor")
        mlflow.log_param("dataset", dataset)
        mlflow.log_param("n_trees", best_n_trees)
        mlflow.log_param("random_state", 42 + i)
        mlflow.log_param("n_jobs", 1)
        mlflow.log_param("run_group", RUN_GROUP)

        # Useful dataset metadata
        mlflow.log_param("n_train", len(x_train))
        mlflow.log_param("n_val_id", len(x_val))
        mlflow.log_param("n_test", len(x_test))
        mlflow.log_param("x_dim", x_train.shape[1])

        # -----------------------------
        # Log metrics
        # -----------------------------
        mlflow.log_metric("val_id_mae", float(best_mae))
        mlflow.log_metric("test_mae", float(mae_test))
        mlflow.log_metric("test_std_abs_error", float(error_std_test))
        mlflow.log_metric("test_se_abs_error", float(error_se_test))
        mlflow.log_metric("runtime_sec", float(runtime_sec))

        # -----------------------------
        # Log artifacts
        # -----------------------------
        # Save result dict as artifact
        artifact_path = f"result_{dataset}.json"
        with open(artifact_path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
        mlflow.log_artifact(artifact_path)

        # Log model
        mlflow.sklearn.log_model(
            sk_model=rf_scorer,
            artifact_path="model"
        )

        # Optional tags for filtering in UI
        mlflow.set_tag("project", "ssl_for_ood_molecules")
        mlflow.set_tag("dataset", dataset)
        mlflow.set_tag("model_family", "rf")
        mlflow.set_tag("split_eval", "val_id_and_test")

        print(f"--> took {round(runtime_sec, 1)} sec")

2026/04/22 17:51:53 INFO mlflow.tracking.fluent: Experiment with name 'ssl_ood_rf_baseline' does not exist. Creating a new experiment.

Predicting for GFP using 3 trees

2026/04/22 17:52:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/22 17:52:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

--> took 19.0 sec
🏃 View run rf_GFP at: http://localhost:5000/#/experiments/1/runs/5125e83f90304c51aaf9b61ffeadfe0a
🧪 View experiment at: http://localhost:5000/#/experiments/1
Predicting for AAV using 3 trees

2026/04/22 17:52:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/22 17:52:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

--> took 0.5 sec
🏃 View run rf_AAV at: http://localhost:5000/#/experiments/1/runs/c75c22eb64914994bece2aaf841b6148
🧪 View experiment at: http://localhost:5000/#/experiments/1
Predicting for TFBind8 using 3 trees

2026/04/22 17:52:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/22 17:52:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

--> took 0.1 sec
🏃 View run rf_TFBind8 at: http://localhost:5000/#/experiments/1/runs/43812ca45ff946c6ac050227725d0d1c
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [9]:
rf_results = {dataset: [] for dataset in datasets}

for i, dataset in enumerate(datasets):
    
    best_mae = float("inf")
    rf_scorer = None
    best_n_trees = None

    x_train = data_dict_np[dataset]["train"]["x"]
    y_train = data_dict_np[dataset]["train"]["y"].ravel()

    x_val = data_dict_np[dataset]["val_id"]["x"]
    y_val = data_dict_np[dataset]["val_id"]["y"].ravel()

    x_test = data_dict_np[dataset]["test"]["x"]
    y_test = data_dict_np[dataset]["test"]["y"].ravel()

    # If you later want tuning, replace this with a loop over candidate values
    n_trees = 3
    
    print(f'Predicting for {dataset} using {n_trees} trees')
    
    start_time = time.time()
    
    rf = RandomForestRegressor(
        n_estimators=n_trees,
        random_state=42 + i,
        n_jobs=1
    )
    rf.fit(x_train, y_train)
    
    y_pred_val = rf.predict(x_val)
    mae_val = mean_absolute_error(y_val, y_pred_val)
    
    if mae_val < best_mae:
        best_mae = mae_val
        rf_scorer = rf
        best_n_trees = n_trees
    
    # Test evaluation
    y_pred_test = rf_scorer.predict(x_test)
    mae_test = mean_absolute_error(y_test, y_pred_test)
    error_std_test = np.std(np.abs(y_pred_test - y_test))
    error_se_test = error_std_test / np.sqrt(len(y_test))
    
    result = {
        "model": "rf",
        "model_num": i,
        "dataset": dataset,
        "hyperparams": {"n_trees": best_n_trees},
        "n_trees": best_n_trees,
        "val_id_mae": float(best_mae),
        "test_mae": float(mae_test),
        "test_std": float(error_std_test),
        "test_se": float(error_se_test),
    }
    
    rf_results[dataset].append(result)
    
    print(f'--> took {round(time.time()-start_time, 1)} sec')

Predicting for GFP using 3 trees
--> took 18.2 sec
Predicting for AAV using 3 trees
--> took 0.5 sec
Predicting for TFBind8 using 3 trees
--> took 0.1 sec

Predicting for GFP using 1111 trees
--> took 7398.9 sec
Predicting for AAV using 1111 trees
--> took 2.1 sec

Predicting for GFP using 11 trees
--> took 369.1 sec
Predicting for AAV using 11 trees
--> took 9.9 sec
Predicting for TFBind8 using 11 trees
--> took 0.4 sec

In [10]:
pd.concat([pd.DataFrame(rf_results[dataset]) for dataset in datasets]).reset_index(drop=True)

,model,model_num,dataset,hyperparams,n_trees,val_id_mae,test_mae,test_std,test_se
0,rf,0,GFP,{'n_trees': 3},3,0.279051,0.669729,0.723311,0.007498
1,rf,1,AAV,{'n_trees': 3},3,0.447648,0.821379,0.613730,0.008804
2,rf,2,TFBind8,{'n_trees': 3},3,0.562154,0.717644,0.566536,0.003644

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from ssl_for_ood.training.trainer import load_config, train_single_run

config = load_config(
    PROJECT_ROOT / "config" / "lstm" / "base.yaml",
    PROJECT_ROOT / "config" / "lstm" / "aav.yaml",
)

config["output"]["run_name"] = "lstm_aav_manual_run"
config["mlflow"]["enabled"] = True   # or False
config["training"]["enable_progress_bar"] = True
config["training"]["epochs"] = 5

metrics, artifacts = train_single_run(config)

Experiment with name ssl-ood-lstm not found. Creating it.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  155 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 155 K
Non-trainable params: 0
Total params: 155 K
Total estimated model params size (MB): 0
Modules in train mode: 9
Modules in eval mode: 0
Total FLOPs: 0

Output()

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

`Trainer.fit` stopped: `max_epochs=5` reached.

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/d336604892be4dffa7268ed180867d70
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

In [1]:
from pathlib import Path
import sys
import time

PROJECT_ROOT = Path.cwd()
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from ssl_for_ood.training.trainer import load_config, train_single_run

# model_class = "lstm"

models_with_errors = ['mlp']
models_working = ['cnn', 'lstm', 'cnn_lstm', 'lstm_cnn', 'transformer']

for model_class in models_with_errors:
    
    print('##################')
    print(f'#####  {model_class.upper()}')
    print('##################')
    
    for d in ['tfbind8', 'aav', 'gfp']:

        print(f'\n### Dataset: {d}\n')

        config = load_config(
            PROJECT_ROOT / "config" / model_class / "base.yaml",
            PROJECT_ROOT / "config" / model_class / f"{d}.yaml",
        )

        config["output"]["run_name"] = f"{model_class}_{d}_manual_run"
        config["mlflow"]["enabled"] = False
        config["training"]["enable_progress_bar"] = True
        config["training"]["epochs"] = 3

        start_time = time.time()
        metrics, artifacts = train_single_run(config)
        print(f'--> took {round(time.time()-start_time, 2)} sec')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\logger_connector\logger_connector.py:76: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

##################
#####  MLP
##################

### Dataset: tfbind8

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  140 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 140 K
Non-trainable params: 0
Total params: 140 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0
Total FLOPs: 0

Output()

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

`Trainer.fit` stopped: `max_epochs=3` reached.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

--> took 14.86 sec

### Dataset: aav

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  275 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 275 K
Non-trainable params: 0
Total params: 275 K
Total estimated model params size (MB): 1
Modules in train mode: 14
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

--> took 19.97 sec

### Dataset: gfp

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  1.4 M │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 1.4 M
Non-trainable params: 0
Total params: 1.4 M
Total estimated model params size (MB): 5
Modules in train mode: 14
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

--> took 23.14 sec

#### One more improvement idea:
- after every run, save that to the results csv file, not just at te end

### Hyperparameter Search

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from ssl_for_ood.training.orchestrator import run_experiments

df = run_experiments(
    project_root=PROJECT_ROOT,
    model_names=["mlp", 'cnn', 'lstm', 'cnn_lstm', 'lstm_cnn', 'transformer'],
    dataset_names=["aav"],
    n_trials=3,
    use_mlflow=True,
)

🚀 Running mlp on aav
[mlp | aav] Trial 1/3

Experiment with name ssl-ood-mlp not found. Creating it.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\training\mlp\aav\mlp_aav_trial_0\checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  550 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 550 K
Non-trainable params: 0
Total params: 550 K
Total estimated model params size (MB): 2
Modules in train mode: 11
Modules in eval mode: 0
Total FLOPs: 0

Output()

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

🏃 View run mlp__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/4/runs/cfd2f6c7836e46b28d3ed368b31fbc18
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[mlp | aav] Trial 2/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 11
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/4/runs/c386046dd96f4caead468b68d39daacb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[mlp | aav] Trial 3/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  104 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 104 K
Non-trainable params: 0
Total params: 104 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/4/runs/1571dc0b7f6e498fa8266061e70dcea2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

🚀 Running cnn on aav
[cnn | aav] Trial 1/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\training\cnn\aav\cnn_aav_trial_0\checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 36.9 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 36.9 K
Non-trainable params: 0
Total params: 36.9 K
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/2/runs/4494922be1c04f5690897020987cfa47
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\training\cnn\aav\cnn_aav_trial_1\checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[cnn | aav] Trial 2/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 55.9 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 55.9 K
Non-trainable params: 0
Total params: 55.9 K
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/2/runs/fe30cf907ab04ff2934423ae6892c63a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[cnn | aav] Trial 3/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 19.9 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 19.9 K
Non-trainable params: 0
Total params: 19.9 K
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/2/runs/009478c9b4d74f9aa5406c9273b45c04
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\training\lstm\aav\lstm_aav_trial_0\checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

🚀 Running lstm on aav
[lstm | aav] Trial 1/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  170 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 170 K
Non-trainable params: 0
Total params: 170 K
Total estimated model params size (MB): 0
Modules in train mode: 9
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/3/runs/0569bafe8a294d0997cbb7137b5e5344
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
[lstm | aav] Trial 2/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\training\lstm\aav\lstm_aav_trial_1\checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  217 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 217 K
Non-trainable params: 0
Total params: 217 K
Total estimated model params size (MB): 0
Modules in train mode: 9
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/3/runs/a995a4daa737487395ed4f665f163326
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
[lstm | aav] Trial 3/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │ 18.6 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 18.6 K
Non-trainable params: 0
Total params: 18.6 K
Total estimated model params size (MB): 0
Modules in train mode: 9
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/3/runs/78c131296f7c41b48d92b806e90893b4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

Experiment with name ssl-ood-cnn-lstm not found. Creating it.

🚀 Running cnn_lstm on aav
[cnn_lstm | aav] Trial 1/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  239 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 239 K
Non-trainable params: 0
Total params: 239 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/5/runs/02608054129146fab661cc45c1602df6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[cnn_lstm | aav] Trial 2/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  108 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 108 K
Non-trainable params: 0
Total params: 108 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/5/runs/ed99f48ab53445ba8e997609555cf028
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5
[cnn_lstm | aav] Trial 3/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  393 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 393 K
Non-trainable params: 0
Total params: 393 K
Total estimated model params size (MB): 1
Modules in train mode: 16
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/5/runs/34ea44e8315646d58aedf1e69fed154c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

Experiment with name ssl-ood-lstm-cnn not found. Creating it.

🚀 Running lstm_cnn on aav
[lstm_cnn | aav] Trial 1/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/6/runs/360079df588f4a60b3178d1b355ca2ca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6
[lstm_cnn | aav] Trial 2/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  231 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 231 K
Non-trainable params: 0
Total params: 231 K
Total estimated model params size (MB): 0
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/6/runs/ff116575d0db4bafb027182cdf2f1796
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6
[lstm_cnn | aav] Trial 3/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  103 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 103 K
Non-trainable params: 0
Total params: 103 K
Total estimated model params size (MB): 0
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/6/runs/e3e6695629d54c719afa880dc254511c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

🚀 Running transformer on aav
[transformer | aav] Trial 1/3

Experiment with name ssl-ood-transformer not found. Creating it.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  279 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 279 K
Non-trainable params: 0
Total params: 279 K
Total estimated model params size (MB): 1
Modules in train mode: 31
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__aav__trial_0 at: http://127.0.0.1:5000/#/experiments/7/runs/0c9caf9d6b214b00987d5e7df239dcb6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7
[transformer | aav] Trial 2/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  213 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 213 K
Non-trainable params: 0
Total params: 213 K
Total estimated model params size (MB): 0
Modules in train mode: 31
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__aav__trial_1 at: http://127.0.0.1:5000/#/experiments/7/runs/84b247d500694dc6817c20800595d13b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[transformer | aav] Trial 3/3

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  115 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 115 K
Non-trainable params: 0
Total params: 115 K
Total estimated model params size (MB): 0
Modules in train mode: 41
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__aav__trial_2 at: http://127.0.0.1:5000/#/experiments/7/runs/4dbf2f78cb434f7d86b032c8b3b19e14
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

✅ Saved results to C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\hyperparameter_search_20260426_045355.csv

In [11]:
import pandas as pd
# pd.read_csv('C:\\Users\\kroep\\Desktop\\AI\\ssl-for-ood-molecules\\results\\hyperparameter_search_20260424_175625.csv')
pd.read_csv('C:\\Users\\kroep\\Desktop\\AI\\ssl-for-ood-molecules\\results\\hyperparameter_search_20260426_045355.csv')

,model,dataset,trial,duration_sec,config,val_id_mae,val_ood_mae,val_id_std,val_ood_std,selected_metric,best_epoch,test_mae,run_dir
0,mlp,aav,0,289.786192,"{""training"": {""batch_size"": 128, ""learning_rat...",0.978137,1.092521,0.849153,0.952246,1.092521,NaN,NaN,results\training\mlp\aav\mlp_aav_trial_0
1,mlp,aav,1,639.084651,"{""training"": {""batch_size"": 32, ""learning_rate...",0.841638,0.860719,0.766619,0.798411,0.860719,NaN,NaN,results\training\mlp\aav\mlp_aav_trial_1
2,mlp,aav,2,1631.008697,"{""training"": {""batch_size"": 32, ""learning_rate...",0.858299,0.973483,0.779051,0.851956,0.973483,NaN,NaN,results\training\mlp\aav\mlp_aav_trial_2
3,cnn,aav,0,528.451471,"{""training"": {""batch_size"": 64, ""learning_rate...",1.474655,1.904841,1.182110,1.487413,1.904841,NaN,NaN,results\training\cnn\aav\cnn_aav_trial_0
4,cnn,aav,1,670.250798,"{""training"": {""batch_size"": 128, ""learning_rat...",0.894690,1.029059,0.798634,0.881874,1.029059,NaN,NaN,results\training\cnn\aav\cnn_aav_trial_1
5,cnn,aav,2,2172.024874,"{""training"": {""batch_size"": 32, ""learning_rate...",1.238528,1.580097,1.050812,1.307495,1.580097,NaN,NaN,results\training\cnn\aav\cnn_aav_trial_2
6,lstm,aav,0,3127.230789,"{""training"": {""batch_size"": 64, ""learning_rate...",0.886277,0.990651,0.812271,0.867238,0.990651,NaN,NaN,results\training\lstm\aav\lstm_aav_trial_0
7,lstm,aav,1,815.381449,"{""training"": {""batch_size"": 128, ""learning_rat...",0.806358,0.853500,0.742979,0.793449,0.853500,NaN,NaN,results\training\lstm\aav\lstm_aav_trial_1
8,lstm,aav,2,1666.285206,"{""training"": {""batch_size"": 32, ""learning_rate...",1.056774,1.254962,0.969375,1.142434,1.254962,NaN,NaN,results\training\lstm\aav\lstm_aav_trial_2
9,cnn_lstm,aav,0,1363.942436,"{""training"": {""batch_size"": 64, ""learning_rate...",0.935697,1.104485,0.861588,1.004989,1.104485,NaN,NaN,results\training\cnn_lstm\aav\cnn_lstm_aav_tri...
10,cnn_lstm,aav,1,549.750133,"{""training"": {""batch_size"": 128, ""learning_rat...",1.178857,1.639110,1.034393,1.419799,1.639110,NaN,NaN,results\training\cnn_lstm\aav\cnn_lstm_aav_tri...
11,cnn_lstm,aav,2,2109.499857,"{""training"": {""batch_size"": 32, ""learning_rate...",1.007978,1.400151,0.932052,1.240797,1.400151,NaN,NaN,results\training\cnn_lstm\aav\cnn_lstm_aav_tri...
12,lstm_cnn,aav,0,2444.518461,"{""training"": {""batch_size"": 64, ""learning_rate...",0.883812,0.931997,0.819967,0.841820,0.931997,NaN,NaN,results\training\lstm_cnn\aav\lstm_cnn_aav_tri...
13,lstm_cnn,aav,1,704.536903,"{""training"": {""batch_size"": 128, ""learning_rat...",1.077259,1.277833,0.927904,1.081720,1.277833,NaN,NaN,results\training\lstm_cnn\aav\lstm_cnn_aav_tri...
14,lstm_cnn,aav,2,1622.901673,"{""training"": {""batch_size"": 32, ""learning_rate...",1.093016,1.310360,0.979428,1.122270,1.310360,NaN,NaN,results\training\lstm_cnn\aav\lstm_cnn_aav_tri...
15,transformer,aav,0,2194.451912,"{""training"": {""batch_size"": 64, ""learning_rate...",0.889972,1.081438,0.817332,0.961715,1.081438,NaN,NaN,results\training\transformer\aav\transformer_a...
16,transformer,aav,1,1230.783247,"{""training"": {""batch_size"": 128, ""learning_rat...",0.898714,1.051147,0.810160,0.948399,1.051147,NaN,NaN,results\training\transformer\aav\transformer_a...
17,transformer,aav,2,3259.170405,"{""training"": {""batch_size"": 32, ""learning_rate...",1.046606,1.429753,0.972239,1.242797,1.429753,NaN,NaN,results\training\transformer\aav\transformer_a...

In [3]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from ssl_for_ood.training.normalization_orchestrator import run_normalization_experiments
from ssl_for_ood.training.trainer import load_config, train_single_run

'''
df = run_normalization_experiments(
    project_root=PROJECT_ROOT,
    model_names=["cnn_lstm"], #["mlp", "cnn", "lstm", "cnn_lstm", "lstm_cnn", "transformer"],
    dataset_names=["aav"], #["tfbind8", "gfp", "aav"],
    strategies=[
        #None,
        #"architecture_native_norm",
        "input_bn",
        "final_bn",
    ],
    use_mlflow=False,
)
'''

'\ndf = run_normalization_experiments(\n    project_root=PROJECT_ROOT,\n    model_names=["cnn_lstm"], #["mlp", "cnn", "lstm", "cnn_lstm", "lstm_cnn", "transformer"],\n    dataset_names=["aav"], #["tfbind8", "gfp", "aav"],\n    strategies=[\n        #None,\n        #"architecture_native_norm",\n        "input_bn",\n        "final_bn",\n    ],\n    use_mlflow=False,\n)\n'

In [10]:
for model_name in ["mlp", 'cnn', 'lstm', 'cnn_lstm', 'lstm_cnn', 'transformer']:
    
    print(f'''
###############
### {model_name}
###############
''')
    
    config = load_config(
        PROJECT_ROOT / "config" / model_name / "base.yaml",
        PROJECT_ROOT / "config" / model_name / "aav.yaml",
    )
    
    for strategy in ["architecture_native_norm", "input_bn", "final_bn", None]:
        
        print(f'\n   --> STRATEGY: "{strategy}"')
        
        config["model"]["normalization_strategy"] = strategy
        config["dataset"]["name"] = "aav"
        config["training"]["epochs"] = 3

        metrics, artifacts = train_single_run(config)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### mlp
###############


   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  276 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 276 K
Non-trainable params: 0
Total params: 276 K
Total estimated model params size (MB): 1
Modules in train mode: 19
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/22f8568c82ba4f858c1ad458a3acfa2f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  276 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 276 K
Non-trainable params: 0
Total params: 276 K
Total estimated model params size (MB): 1
Modules in train mode: 16
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/7fb3dbd310864104b900baf6119ce112
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  275 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 275 K
Non-trainable params: 0
Total params: 275 K
Total estimated model params size (MB): 1
Modules in train mode: 16
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/a66796d299234928968b258e36a6ab2e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  275 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 275 K
Non-trainable params: 0
Total params: 275 K
Total estimated model params size (MB): 1
Modules in train mode: 16
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/92bbaf59d6d94ff8b60d48d00f7baf75
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### cnn
###############


   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 71.7 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 71.7 K
Non-trainable params: 0
Total params: 71.7 K
Total estimated model params size (MB): 0
Modules in train mode: 23
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/903495ee68e04173845c46cdfe33c657
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 71.3 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 71.3 K
Non-trainable params: 0
Total params: 71.3 K
Total estimated model params size (MB): 0
Modules in train mode: 21
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/31a515540630431fa3fad12775222e23
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 71.5 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 71.5 K
Non-trainable params: 0
Total params: 71.5 K
Total estimated model params size (MB): 0
Modules in train mode: 20
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/db69a71038a6466282aa5cf526ee1430
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 71.3 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 71.3 K
Non-trainable params: 0
Total params: 71.3 K
Total estimated model params size (MB): 0
Modules in train mode: 20
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/70bc11329ef34ed5b851c960c072704f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### lstm
###############


   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  156 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 156 K
Non-trainable params: 0
Total params: 156 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/0a30ddeded7f4d16b47f3273b90458a5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  155 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 155 K
Non-trainable params: 0
Total params: 155 K
Total estimated model params size (MB): 0
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/f4ba2e4b14704d8ea67a7b4e737f2f6f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  156 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 156 K
Non-trainable params: 0
Total params: 156 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/acb373d84c0648b780a2be9f980a7244
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  155 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 155 K
Non-trainable params: 0
Total params: 155 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/6f588c443a5040e9966636d4a44eacc8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### cnn_lstm
###############


   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  994 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 994 K
Non-trainable params: 0
Total params: 994 K
Total estimated model params size (MB): 3
Modules in train mode: 20
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/37f122b54006418dac9567b49be116a3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  994 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 994 K
Non-trainable params: 0
Total params: 994 K
Total estimated model params size (MB): 3
Modules in train mode: 19
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/5bdd896d0ba34201b3b52b68512b606f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  994 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 994 K
Non-trainable params: 0
Total params: 994 K
Total estimated model params size (MB): 3
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/5647383ae2184a539f9973e3f6fbce5b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  993 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 993 K
Non-trainable params: 0
Total params: 993 K
Total estimated model params size (MB): 3
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/f7d404261e6e479982b92d57c81d6850
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### lstm_cnn
###############


   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  107 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 107 K
Non-trainable params: 0
Total params: 107 K
Total estimated model params size (MB): 0
Modules in train mode: 26
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/a1e4120cd4744893bd904f9b5a930806
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

   --> STRATEGY: "input_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  106 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 106 K
Non-trainable params: 0
Total params: 106 K
Total estimated model params size (MB): 0
Modules in train mode: 24
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/5721965782dd497d8e409416155281b5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  107 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 107 K
Non-trainable params: 0
Total params: 107 K
Total estimated model params size (MB): 0
Modules in train mode: 23
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/cb1788fd3eb8430fa531599e3ec389e4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  106 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 106 K
Non-trainable params: 0
Total params: 106 K
Total estimated model params size (MB): 0
Modules in train mode: 23
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/5a5bf8b91d624acbb760493f4ab9a95f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

###############
### transformer
###############


   --> STRATEGY: "architecture_native_norm"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  105 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 105 K
Non-trainable params: 0
Total params: 105 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/1f7bb74b198541c288db23ebe8245383
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  105 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 105 K
Non-trainable params: 0
Total params: 105 K
Total estimated model params size (MB): 0
Modules in train mode: 34
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/5b18233dc4be4cb1a1f40cd8ffce1be3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  105 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 105 K
Non-trainable params: 0
Total params: 105 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/76c84484ca9a4d58954b7250a5a676e3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  105 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 105 K
Non-trainable params: 0
Total params: 105 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

`Trainer.fit` stopped: `max_epochs=3` reached.

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/f0b3c8c20b104b1bba03c2f167fa90d8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

### Experiment 1: BN and LN for best hyperparameter settings

In [1]:
from pathlib import Path
import sys
import json
import ast
import pandas as pd

PROJECT_ROOT = Path.cwd()

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

# from ssl_for_ood.training.trainer import load_config, train_single_run
from ssl_for_ood.training.normalization_orchestrator import run_normalization_from_best_configs

df_norm = run_normalization_from_best_configs(
    project_root=PROJECT_ROOT,
    search_results_path=PROJECT_ROOT / "results" / "hyperparameter_search_20260426_045355.csv",
    dataset_name="aav",
)

###############
### cnn
###############

   --> STRATEGY: "architecture_native_norm"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 56.3 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 56.3 K
Non-trainable params: 0
Total params: 56.3 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0
Total FLOPs: 0

Output()

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:
434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of
the `num_workers` argument` to `num_workers=5` in the `DataLoader` to improve performance.

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/525cdcfbdb3c456490e38a806a7f5ce5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

C:\Users\kroep\anaconda3\envs\ssl_ood_env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

   --> STRATEGY: "input_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 56.0 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 56.0 K
Non-trainable params: 0
Total params: 56.0 K
Total estimated model params size (MB): 0
Modules in train mode: 18
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/3ddc859d60e54f77a328d784a35b9ba9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 56.1 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 56.1 K
Non-trainable params: 0
Total params: 56.1 K
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/87cd317c92d4423d8888b5d949c626c7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNRegressor │ 55.9 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 55.9 K
Non-trainable params: 0
Total params: 55.9 K
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn__manual at: http://127.0.0.1:5000/#/experiments/2/runs/d122f20b9bb548eba2c827181d2ce03f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### cnn_lstm
###############

   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  240 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 240 K
Non-trainable params: 0
Total params: 240 K
Total estimated model params size (MB): 0
Modules in train mode: 24
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/ef60835deae9434787d5e3278905b7dc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "input_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  239 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 239 K
Non-trainable params: 0
Total params: 239 K
Total estimated model params size (MB): 0
Modules in train mode: 22
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/60d3abddba7f43bcbd3bd46d0723f810
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5
   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  240 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 240 K
Non-trainable params: 0
Total params: 240 K
Total estimated model params size (MB): 0
Modules in train mode: 21
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/f65b678fd25a44be848242a193d0297b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "None"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ CNNLSTMRegressor │  239 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 239 K
Non-trainable params: 0
Total params: 239 K
Total estimated model params size (MB): 0
Modules in train mode: 21
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run cnn_lstm__manual at: http://127.0.0.1:5000/#/experiments/5/runs/2e48b80fff07430982a2bbb1c2bf2d17
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/5

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

###############
### lstm
###############

   --> STRATEGY: "architecture_native_norm"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  217 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 217 K
Non-trainable params: 0
Total params: 217 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/055f09cb854949d08bc721971fd97201
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

GPU available: True (cuda), used: True

   --> STRATEGY: "input_bn"

TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  217 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 217 K
Non-trainable params: 0
Total params: 217 K
Total estimated model params size (MB): 0
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/79c8ad1fea8e49e8be8f01cece802cf6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  217 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 217 K
Non-trainable params: 0
Total params: 217 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/9f0170e2e4ce4645a57151a6eeb16163
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMRegressor │  217 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss       │      0 │ train │     0 │
└───┴─────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 217 K
Non-trainable params: 0
Total params: 217 K
Total estimated model params size (MB): 0
Modules in train mode: 12
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm__manual at: http://127.0.0.1:5000/#/experiments/3/runs/f97ddae3bf934e24895cc961bdabed7c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

###############
### lstm_cnn
###############

   --> STRATEGY: "architecture_native_norm"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 22
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/b9624faf1b494f01811bd843e23df053
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6
   --> STRATEGY: "input_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 21
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/7e2ecee7c3c148a58b46b885f51d7cc9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   --> STRATEGY: "final_bn"

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 20
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/b6970b124fa44cd39c490f6897b9a3b0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6
   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type             ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ LSTMCNNRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss          │      0 │ train │     0 │
└───┴─────────┴──────────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 20
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run lstm_cnn__manual at: http://127.0.0.1:5000/#/experiments/6/runs/5a8d578411274ee2a52ff019db9aa49d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6

###############
### mlp
###############

   --> STRATEGY: "architecture_native_norm"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  210 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 210 K
Non-trainable params: 0
Total params: 210 K
Total estimated model params size (MB): 0
Modules in train mode: 15
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/dd1e8fca51e849c0a23a781c6d300912
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
   --> STRATEGY: "input_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  210 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 210 K
Non-trainable params: 0
Total params: 210 K
Total estimated model params size (MB): 0
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/fb8fff5d11da45c48d379ca5e1876953
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  210 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 210 K
Non-trainable params: 0
Total params: 210 K
Total estimated model params size (MB): 0
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/1d15cb9b27ca4eed9a0d90b6c1f14ee9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ MLPRegressor │  209 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss      │      0 │ train │     0 │
└───┴─────────┴──────────────┴────────┴───────┴───────┘

Trainable params: 209 K
Non-trainable params: 0
Total params: 209 K
Total estimated model params size (MB): 0
Modules in train mode: 13
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run mlp__manual at: http://127.0.0.1:5000/#/experiments/4/runs/17acc0d6c96e4cbd9b38fd813f50b8db
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

###############
### transformer
###############

   --> STRATEGY: "architecture_native_norm"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  213 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 213 K
Non-trainable params: 0
Total params: 213 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/a521174160c6490dbc1ebab324635e09
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7
   --> STRATEGY: "input_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  214 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 214 K
Non-trainable params: 0
Total params: 214 K
Total estimated model params size (MB): 0
Modules in train mode: 34
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/cdb6826d4147402bb20dfe7b718e070e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7
   --> STRATEGY: "final_bn"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  214 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 214 K
Non-trainable params: 0
Total params: 214 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/fa0951e8a05f47098c61f97ce9636172
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7
   --> STRATEGY: "None"

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type                 ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ TransformerRegressor │  213 K │ train │     0 │
│ 1 │ loss_fn │ MSELoss              │      0 │ train │     0 │
└───┴─────────┴──────────────────────┴────────┴───────┴───────┘

Trainable params: 213 K
Non-trainable params: 0
Total params: 213 K
Total estimated model params size (MB): 0
Modules in train mode: 33
Modules in eval mode: 0
Total FLOPs: 0

Output()

🏃 View run transformer__manual at: http://127.0.0.1:5000/#/experiments/7/runs/42cfae9e62c04007b204720197734170
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7

✅ Saved normalization results to C:\Users\kroep\Desktop\AI\ssl-for-ood-molecules\results\normalization_from_best_aav_20260430_003028.csv

In [1]:
import pandas as pd
df_norm = pd.read_csv('C:\\Users\\kroep\\Desktop\\AI\\ssl-for-ood-molecules\\results\\normalization_from_best_aav_20260430_003028.csv')

In [7]:
df_norm.sort_values('val_ood_mae')

,model,dataset,normalization_strategy,duration_sec,val_id_mae,val_ood_mae,test_mae,val_id_std_abs_error,val_ood_std_abs_error,test_std_abs_error,run_dir
10,lstm,aav,final_bn,847.349832,0.793860,0.807032,NaN,0.743731,0.738349,NaN,results\training\lstm\aav\20260429_200426
9,lstm,aav,input_bn,543.227698,0.788206,0.829678,NaN,0.740845,0.773375,NaN,results\training\lstm\aav\20260429_195523
11,lstm,aav,NaN,643.805017,0.797056,0.847245,NaN,0.742440,0.783192,NaN,results\training\lstm\aav\20260429_201833
13,lstm_cnn,aav,input_bn,2119.971410,0.814337,0.855202,NaN,0.772425,0.774230,NaN,results\training\lstm_cnn\aav\20260429_205827
2,cnn,aav,final_bn,719.427601,0.800898,0.869613,NaN,0.725678,0.775935,NaN,results\training\cnn\aav\20260429_181215
8,lstm,aav,architecture_native_norm,730.775943,0.797066,0.871531,NaN,0.732724,0.803768,NaN,results\training\lstm\aav\20260429_194312
16,mlp,aav,architecture_native_norm,1384.428490,0.815231,0.879079,NaN,0.740319,0.773760,NaN,results\training\mlp\aav\20260429_224428
19,mlp,aav,NaN,605.092372,0.836381,0.895930,NaN,0.772084,0.795483,NaN,results\training\mlp\aav\20260429_233025
1,cnn,aav,input_bn,545.378868,0.830036,0.901543,NaN,0.754924,0.782579,NaN,results\training\cnn\aav\20260429_180310
18,mlp,aav,final_bn,941.330916,0.835502,0.918007,NaN,0.758974,0.825776,NaN,results\training\mlp\aav\20260429_231443
0,cnn,aav,architecture_native_norm,255.602809,0.844793,0.921726,NaN,0.771924,0.793598,NaN,results\training\cnn\aav\20260429_175854
15,lstm_cnn,aav,NaN,2426.288453,0.883812,0.931997,NaN,0.819967,0.841820,NaN,results\training\lstm_cnn\aav\20260429_220402
3,cnn,aav,NaN,529.911274,0.865184,0.962309,NaN,0.779956,0.829530,NaN,results\training\cnn\aav\20260429_182414
14,lstm_cnn,aav,final_bn,1814.821961,0.870106,0.964875,NaN,0.806777,0.856435,NaN,results\training\lstm_cnn\aav\20260429_213347
12,lstm_cnn,aav,architecture_native_norm,1749.978573,0.879822,0.986589,NaN,0.797561,0.855209,NaN,results\training\lstm_cnn\aav\20260429_202917
21,transformer,aav,input_bn,850.825953,0.901148,1.078771,NaN,0.818265,0.962340,NaN,results\training\transformer\aav\20260429_235211
23,transformer,aav,NaN,709.715972,0.917544,1.080765,NaN,0.837111,0.968887,NaN,results\training\transformer\aav\20260430_001838
20,transformer,aav,architecture_native_norm,700.757862,0.917544,1.080765,NaN,0.837111,0.968887,NaN,results\training\transformer\aav\20260429_234030
7,cnn_lstm,aav,NaN,1368.064842,0.935697,1.104485,NaN,0.861588,1.004989,NaN,results\training\cnn_lstm\aav\20260429_192024
22,transformer,aav,final_bn,737.032108,0.904976,1.105379,NaN,0.825272,0.985282,NaN,results\training\transformer\aav\20260430_000621
5,cnn_lstm,aav,input_bn,1032.831557,0.949807,1.158798,NaN,0.864152,1.037596,NaN,results\training\cnn_lstm\aav\20260429_184655
6,cnn_lstm,aav,final_bn,975.378326,1.016772,1.330689,NaN,0.914128,1.169556,NaN,results\training\cnn_lstm\aav\20260429_190408
4,cnn_lstm,aav,architecture_native_norm,831.083285,1.019122,1.391930,NaN,0.927741,1.248771,NaN,results\training\cnn_lstm\aav\20260429_183304
17,mlp,aav,input_bn,430.955893,6.685074,6.461037,NaN,14.512560,14.088759,NaN,results\training\mlp\aav\20260429_230732

In [6]:
df_norm.iloc[int(df_norm.val_ood_mae.argmin())]

model                                                          lstm
dataset                                                         aav
normalization_strategy                                     final_bn
duration_sec                                             847.349832
val_id_mae                                                  0.79386
val_ood_mae                                                0.807032
test_mae                                                        NaN
val_id_std_abs_error                                       0.743731
val_ood_std_abs_error                                      0.738349
test_std_abs_error                                              NaN
run_dir                   results\training\lstm\aav\20260429_200426
Name: 10, dtype: object

In [2]:
for model in df_norm.model.unique():
    for normalization_strategy in df_norm.normalization_strategy.unique():

,model,dataset,normalization_strategy,duration_sec,val_id_mae,val_ood_mae,test_mae,val_id_std_abs_error,val_ood_std_abs_error,test_std_abs_error,run_dir
0,cnn,aav,architecture_native_norm,255.602809,0.844793,0.921726,NaN,0.771924,0.793598,NaN,results\training\cnn\aav\20260429_175854
1,cnn,aav,input_bn,545.378868,0.830036,0.901543,NaN,0.754924,0.782579,NaN,results\training\cnn\aav\20260429_180310
2,cnn,aav,final_bn,719.427601,0.800898,0.869613,NaN,0.725678,0.775935,NaN,results\training\cnn\aav\20260429_181215
3,cnn,aav,NaN,529.911274,0.865184,0.962309,NaN,0.779956,0.829530,NaN,results\training\cnn\aav\20260429_182414
4,cnn_lstm,aav,architecture_native_norm,831.083285,1.019122,1.391930,NaN,0.927741,1.248771,NaN,results\training\cnn_lstm\aav\20260429_183304
5,cnn_lstm,aav,input_bn,1032.831557,0.949807,1.158798,NaN,0.864152,1.037596,NaN,results\training\cnn_lstm\aav\20260429_184655
6,cnn_lstm,aav,final_bn,975.378326,1.016772,1.330689,NaN,0.914128,1.169556,NaN,results\training\cnn_lstm\aav\20260429_190408
7,cnn_lstm,aav,NaN,1368.064842,0.935697,1.104485,NaN,0.861588,1.004989,NaN,results\training\cnn_lstm\aav\20260429_192024
8,lstm,aav,architecture_native_norm,730.775943,0.797066,0.871531,NaN,0.732724,0.803768,NaN,results\training\lstm\aav\20260429_194312
9,lstm,aav,input_bn,543.227698,0.788206,0.829678,NaN,0.740845,0.773375,NaN,results\training\lstm\aav\20260429_195523
10,lstm,aav,final_bn,847.349832,0.793860,0.807032,NaN,0.743731,0.738349,NaN,results\training\lstm\aav\20260429_200426
11,lstm,aav,NaN,643.805017,0.797056,0.847245,NaN,0.742440,0.783192,NaN,results\training\lstm\aav\20260429_201833
12,lstm_cnn,aav,architecture_native_norm,1749.978573,0.879822,0.986589,NaN,0.797561,0.855209,NaN,results\training\lstm_cnn\aav\20260429_202917
13,lstm_cnn,aav,input_bn,2119.971410,0.814337,0.855202,NaN,0.772425,0.774230,NaN,results\training\lstm_cnn\aav\20260429_205827
14,lstm_cnn,aav,final_bn,1814.821961,0.870106,0.964875,NaN,0.806777,0.856435,NaN,results\training\lstm_cnn\aav\20260429_213347
15,lstm_cnn,aav,NaN,2426.288453,0.883812,0.931997,NaN,0.819967,0.841820,NaN,results\training\lstm_cnn\aav\20260429_220402
16,mlp,aav,architecture_native_norm,1384.428490,0.815231,0.879079,NaN,0.740319,0.773760,NaN,results\training\mlp\aav\20260429_224428
17,mlp,aav,input_bn,430.955893,6.685074,6.461037,NaN,14.512560,14.088759,NaN,results\training\mlp\aav\20260429_230732
18,mlp,aav,final_bn,941.330916,0.835502,0.918007,NaN,0.758974,0.825776,NaN,results\training\mlp\aav\20260429_231443
19,mlp,aav,NaN,605.092372,0.836381,0.895930,NaN,0.772084,0.795483,NaN,results\training\mlp\aav\20260429_233025
20,transformer,aav,architecture_native_norm,700.757862,0.917544,1.080765,NaN,0.837111,0.968887,NaN,results\training\transformer\aav\20260429_234030
21,transformer,aav,input_bn,850.825953,0.901148,1.078771,NaN,0.818265,0.962340,NaN,results\training\transformer\aav\20260429_235211
22,transformer,aav,final_bn,737.032108,0.904976,1.105379,NaN,0.825272,0.985282,NaN,results\training\transformer\aav\20260430_000621
23,transformer,aav,NaN,709.715972,0.917544,1.080765,NaN,0.837111,0.968887,NaN,results\training\transformer\aav\20260430_001838